version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 100
  ignore:
  - dependency-name: Celeste.Misc.Utils
    versions:
    - 2.1.0
  - dependency-name: JetBrains.Annotations
    versions:
    - 2020.3.0
